// <auto-generated />
using System;
using Antreman.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Antreman.Migrations
{
    [DbContext(typeof(antremanDBContext))]
    [Migration("20230210223252_uc")]
    partial class uc
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Antreman.Models.Category", b =>
                {
                    b.Property<int>("CategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryID"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("CategoryID");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryID = 1,
                            CategoryName = "Günlük Antremanlar"
                        },
                        new
                        {
                            CategoryID = 2,
                            CategoryName = "Programlar"
                        });
                });

            modelBuilder.Entity("Antreman.Models.City", b =>
                {
                    b.Property<int>("CityID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CityID"));

                    b.Property<string>("CityName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("CityID");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            CityID = 1,
                            CityName = "Adana"
                        },
                        new
                        {
                            CityID = 6,
                            CityName = "Ankara"
                        },
                        new
                        {
                            CityID = 7,
                            CityName = "Antalya"
                        },
                        new
                        {
                            CityID = 16,
                            CityName = "Bursa"
                        },
                        new
                        {
                            CityID = 26,
                            CityName = "Eskişehir"
                        },
                        new
                        {
                            CityID = 27,
                            CityName = "Gaziantep"
                        },
                        new
                        {
                            CityID = 34,
                            CityName = "İstanbul"
                        },
                        new
                        {
                            CityID = 35,
                            CityName = "İzmir"
                        },
                        new
                        {
                            CityID = 41,
                            CityName = "Kocaeli"
                        },
                        new
                        {
                            CityID = 33,
                            CityName = "Mersin"
                        },
                        new
                        {
                            CityID = 48,
                            CityName = "Muğla"
                        },
                        new
                        {
                            CityID = 54,
                            CityName = "Sakarya"
                        },
                        new
                        {
                            CityID = 55,
                            CityName = "Samsun"
                        });
                });

            modelBuilder.Entity("Antreman.Models.Commentt", b =>
                {
                    b.Property<int>("CommenttID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CommenttID"));

                    b.Property<DateTime>("CommenttDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CommenttText")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<int>("FitnessCenterID")
                        .HasColumnType("int");

                    b.Property<int>("UserrID")
                        .HasColumnType("int");

                    b.HasKey("CommenttID");

                    b.HasIndex("FitnessCenterID");

                    b.HasIndex("UserrID");

                    b.ToTable("Commentts");
                });

            modelBuilder.Entity("Antreman.Models.District", b =>
                {
                    b.Property<int>("DistrictID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DistrictID"));

                    b.Property<int>("CityID")
                        .HasColumnType("int");

                    b.Property<string>("DistrictName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("DistrictID");

                    b.HasIndex("CityID");

                    b.ToTable("Districts");

                    b.HasData(
                        new
                        {
                            DistrictID = 1,
                            CityID = 1,
                            DistrictName = "Seyhan"
                        },
                        new
                        {
                            DistrictID = 2,
                            CityID = 1,
                            DistrictName = "Yüreğir"
                        },
                        new
                        {
                            DistrictID = 3,
                            CityID = 6,
                            DistrictName = "Çankaya"
                        },
                        new
                        {
                            DistrictID = 4,
                            CityID = 6,
                            DistrictName = "Etimesgut"
                        },
                        new
                        {
                            DistrictID = 5,
                            CityID = 6,
                            DistrictName = "Mamak"
                        },
                        new
                        {
                            DistrictID = 6,
                            CityID = 6,
                            DistrictName = "Yenimahalle"
                        },
                        new
                        {
                            DistrictID = 7,
                            CityID = 7,
                            DistrictName = "Kepez"
                        },
                        new
                        {
                            DistrictID = 8,
                            CityID = 7,
                            DistrictName = "Muratpaşa"
                        },
                        new
                        {
                            DistrictID = 9,
                            CityID = 16,
                            DistrictName = "Nilüfer"
                        },
                        new
                        {
                            DistrictID = 10,
                            CityID = 26,
                            DistrictName = "Tepebaşı"
                        },
                        new
                        {
                            DistrictID = 11,
                            CityID = 27,
                            DistrictName = "Şehitkamil"
                        },
                        new
                        {
                            DistrictID = 12,
                            CityID = 34,
                            DistrictName = "Ataşehir"
                        },
                        new
                        {
                            DistrictID = 13,
                            CityID = 34,
                            DistrictName = "Bahçelievler"
                        },
                        new
                        {
                            DistrictID = 14,
                            CityID = 34,
                            DistrictName = "Bakırköy"
                        },
                        new
                        {
                            DistrictID = 15,
                            CityID = 34,
                            DistrictName = "Başakşehir"
                        },
                        new
                        {
                            DistrictID = 16,
                            CityID = 34,
                            DistrictName = "Bayrampaşa"
                        },
                        new
                        {
                            DistrictID = 17,
                            CityID = 34,
                            DistrictName = "Beşiktaş"
                        },
                        new
                        {
                            DistrictID = 18,
                            CityID = 34,
                            DistrictName = "Beykoz"
                        },
                        new
                        {
                            DistrictID = 19,
                            CityID = 34,
                            DistrictName = "Beyoğlu"
                        },
                        new
                        {
                            DistrictID = 20,
                            CityID = 34,
                            DistrictName = "Esenyurt"
                        },
                        new
                        {
                            DistrictID = 21,
                            CityID = 34,
                            DistrictName = "Eyüp"
                        },
                        new
                        {
                            DistrictID = 22,
                            CityID = 34,
                            DistrictName = "Güngören"
                        },
                        new
                        {
                            DistrictID = 23,
                            CityID = 34,
                            DistrictName = "Kadıköy"
                        },
                        new
                        {
                            DistrictID = 24,
                            CityID = 34,
                            DistrictName = "Kağıthane"
                        },
                        new
                        {
                            DistrictID = 25,
                            CityID = 34,
                            DistrictName = "Kartal"
                        },
                        new
                        {
                            DistrictID = 26,
                            CityID = 34,
                            DistrictName = "Küçükçekmece"
                        },
                        new
                        {
                            DistrictID = 27,
                            CityID = 34,
                            DistrictName = "Maltepe"
                        },
                        new
                        {
                            DistrictID = 28,
                            CityID = 34,
                            DistrictName = "Pendik"
                        },
                        new
                        {
                            DistrictID = 29,
                            CityID = 34,
                            DistrictName = "Sarıyer"
                        },
                        new
                        {
                            DistrictID = 30,
                            CityID = 34,
                            DistrictName = "Şişli"
                        },
                        new
                        {
                            DistrictID = 31,
                            CityID = 34,
                            DistrictName = "Sultanbeyli"
                        },
                        new
                        {
                            DistrictID = 32,
                            CityID = 34,
                            DistrictName = "Sultangazi"
                        },
                        new
                        {
                            DistrictID = 33,
                            CityID = 34,
                            DistrictName = "Ümraniye"
                        },
                        new
                        {
                            DistrictID = 34,
                            CityID = 34,
                            DistrictName = "Üsküdar"
                        },
                        new
                        {
                            DistrictID = 35,
                            CityID = 35,
                            DistrictName = "Balçova"
                        },
                        new
                        {
                            DistrictID = 36,
                            CityID = 35,
                            DistrictName = "Bornova"
                        },
                        new
                        {
                            DistrictID = 37,
                            CityID = 35,
                            DistrictName = "Buca"
                        },
                        new
                        {
                            DistrictID = 38,
                            CityID = 35,
                            DistrictName = "Çiğli"
                        },
                        new
                        {
                            DistrictID = 39,
                            CityID = 35,
                            DistrictName = "Gaziemir"
                        },
                        new
                        {
                            DistrictID = 40,
                            CityID = 35,
                            DistrictName = "Konak"
                        },
                        new
                        {
                            DistrictID = 41,
                            CityID = 41,
                            DistrictName = "Gebze"
                        },
                        new
                        {
                            DistrictID = 42,
                            CityID = 41,
                            DistrictName = "İzmit"
                        },
                        new
                        {
                            DistrictID = 43,
                            CityID = 33,
                            DistrictName = "Yenişehir"
                        },
                        new
                        {
                            DistrictID = 44,
                            CityID = 48,
                            DistrictName = "Bodrum"
                        },
                        new
                        {
                            DistrictID = 45,
                            CityID = 54,
                            DistrictName = "Sedirvan"
                        },
                        new
                        {
                            DistrictID = 46,
                            CityID = 55,
                            DistrictName = "Canik"
                        });
                });

            modelBuilder.Entity("Antreman.Models.Favoritee", b =>
                {
                    b.Property<int>("FavoriteeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FavoriteeID"));

                    b.Property<DateTime>("FavoriteeDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("FitnessCenterID")
                        .HasColumnType("int");

                    b.Property<int>("UserrID")
                        .HasColumnType("int");

                    b.HasKey("FavoriteeID");

                    b.HasIndex("FitnessCenterID");

                    b.HasIndex("UserrID");

                    b.ToTable("Favoritees");
                });

            modelBuilder.Entity("Antreman.Models.FitnessCenter", b =>
                {
                    b.Property<int>("FitnessCenterID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FitnessCenterID"));

                    b.Property<int?>("Capacity")
                        .HasColumnType("int");

                    b.Property<int>("DistrictID")
                        .HasColumnType("int");

                    b.Property<string>("FitnessCenterAdress")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FitnessCenterName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("FitnessCenterID");

                    b.HasIndex("DistrictID");

                    b.ToTable("FitnessCenters");

                    b.HasData(
                        new
                        {
                            FitnessCenterID = 1,
                            Capacity = 250,
                            DistrictID = 1,
                            FitnessCenterAdress = "Ahmet Remzi Yüreğir, Turhan Cemal Beriker Blv. No:1",
                            FitnessCenterName = "01 Burda"
                        },
                        new
                        {
                            FitnessCenterID = 2,
                            Capacity = 200,
                            DistrictID = 2,
                            FitnessCenterAdress = "Sinanpaşa, Hacı Sabancı Blv. No:28",
                            FitnessCenterName = "Adana Optimum"
                        },
                        new
                        {
                            FitnessCenterID = 3,
                            Capacity = 200,
                            DistrictID = 3,
                            FitnessCenterAdress = "Prof. Dr. Ahmet Taner Kışlalı, Safranbolu Cd. No:12",
                            FitnessCenterName = "Konutkent"
                        },
                        new
                        {
                            FitnessCenterID = 4,
                            Capacity = 200,
                            DistrictID = 3,
                            FitnessCenterAdress = "Koru, Ankaralılar Cd. No:2",
                            FitnessCenterName = "Gordion"
                        },
                        new
                        {
                            FitnessCenterID = 5,
                            Capacity = 200,
                            DistrictID = 3,
                            FitnessCenterAdress = "Eskişehir Yolu Mustafa Kemal Mah. 2123 Sokak No: 2",
                            FitnessCenterName = "Cepa"
                        },
                        new
                        {
                            FitnessCenterID = 6,
                            Capacity = 200,
                            DistrictID = 3,
                            FitnessCenterAdress = "Oran, Panora Alışveriş ve Yaşam Merkezi, Turan Güneş Blv. No:182 D:2",
                            FitnessCenterName = "Panora"
                        },
                        new
                        {
                            FitnessCenterID = 7,
                            Capacity = 200,
                            DistrictID = 3,
                            FitnessCenterAdress = "Yapı Kredi Koray, İş Merkezi 8/A",
                            FitnessCenterName = "Tunalı"
                        },
                        new
                        {
                            FitnessCenterID = 8,
                            Capacity = 200,
                            DistrictID = 3,
                            FitnessCenterAdress = "Birlik Mah. 428.Cad. No:41",
                            FitnessCenterName = "365 AVM"
                        },
                        new
                        {
                            FitnessCenterID = 9,
                            Capacity = 200,
                            DistrictID = 4,
                            FitnessCenterAdress = "Eryaman, Samsun 19 Mayıs Cd. No:5",
                            FitnessCenterName = "Eryaman"
                        },
                        new
                        {
                            FitnessCenterID = 10,
                            Capacity = 200,
                            DistrictID = 5,
                            FitnessCenterAdress = "Akşemsettin Mah., Nata Vega Outlet",
                            FitnessCenterName = "Nata Vega"
                        },
                        new
                        {
                            FitnessCenterID = 11,
                            Capacity = 200,
                            DistrictID = 6,
                            FitnessCenterAdress = "Ankamall AVM Konya Devlet Karayolu Üzeri Akköprü Mevkii",
                            FitnessCenterName = "AnkaMALL"
                        },
                        new
                        {
                            FitnessCenterID = 12,
                            Capacity = 200,
                            DistrictID = 6,
                            FitnessCenterAdress = "Armada AVM Eskişehir Yolu No: 6",
                            FitnessCenterName = "Armada"
                        },
                        new
                        {
                            FitnessCenterID = 13,
                            Capacity = 200,
                            DistrictID = 6,
                            FitnessCenterAdress = "Podium AVM Macun Mah. Bağdat Cad. No: 60",
                            FitnessCenterName = "Podium"
                        },
                        new
                        {
                            FitnessCenterID = 14,
                            Capacity = 200,
                            DistrictID = 7,
                            FitnessCenterAdress = "Erasta AVM Ahatlı Mah., Dumlupınar Blv., Yanyolu No:25",
                            FitnessCenterName = "Erasta"
                        },
                        new
                        {
                            FitnessCenterID = 15,
                            Capacity = 200,
                            DistrictID = 8,
                            FitnessCenterAdress = "Şirinyalı Mah. İsmet Gökşen Cad. Carrefoursa Avm No:5",
                            FitnessCenterName = "Lara Carrefour"
                        },
                        new
                        {
                            FitnessCenterID = 16,
                            Capacity = 200,
                            DistrictID = 8,
                            FitnessCenterAdress = "Tahılpazarı Mah. Kazım Özalp Cad. (Şarampol) No:84",
                            FitnessCenterName = "Marka Antalya"
                        },
                        new
                        {
                            FitnessCenterID = 17,
                            Capacity = 200,
                            DistrictID = 9,
                            FitnessCenterAdress = "Odunluk Mah. Bursa Carrefoursa AVM",
                            FitnessCenterName = "Nilüfer Carrefour"
                        },
                        new
                        {
                            FitnessCenterID = 18,
                            Capacity = 200,
                            DistrictID = 9,
                            FitnessCenterAdress = "Cumhuriyet Mah. Nilüfer Hatun Cad. No:114",
                            FitnessCenterName = "Podyum Park"
                        },
                        new
                        {
                            FitnessCenterID = 19,
                            Capacity = 200,
                            DistrictID = 10,
                            FitnessCenterAdress = "Hoşnudiye Mah. İsmet İnönü 1 Cad. No:131 /1C-1D-1E",
                            FitnessCenterName = "Eskişehir"
                        },
                        new
                        {
                            FitnessCenterID = 20,
                            Capacity = 200,
                            DistrictID = 11,
                            FitnessCenterAdress = "Sankopark AVM 4.Kat",
                            FitnessCenterName = "Sankopark"
                        },
                        new
                        {
                            FitnessCenterID = 21,
                            Capacity = 200,
                            DistrictID = 12,
                            FitnessCenterAdress = "Küçükbakkalköy Mah., Dudullu Cad. 23-25",
                            FitnessCenterName = "Brandium"
                        },
                        new
                        {
                            FitnessCenterID = 22,
                            Capacity = 200,
                            DistrictID = 12,
                            FitnessCenterAdress = "Barbaros Mah. Ahlat Sok.",
                            FitnessCenterName = "Watergarden"
                        },
                        new
                        {
                            FitnessCenterID = 23,
                            Capacity = 200,
                            DistrictID = 13,
                            FitnessCenterAdress = "Bahçelievler Mahallesi, Şair Orhan Veli Sok. No:22",
                            FitnessCenterName = "Ömür Plaza"
                        },
                        new
                        {
                            FitnessCenterID = 24,
                            Capacity = 200,
                            DistrictID = 13,
                            FitnessCenterAdress = "Yenibosna Koçtaş, Fevzi Çakmak Mah. Yıldırım Beyazıd Cad. No:1",
                            FitnessCenterName = "Yenibosna Koçtaş"
                        },
                        new
                        {
                            FitnessCenterID = 25,
                            Capacity = 200,
                            DistrictID = 14,
                            FitnessCenterAdress = "Yenimahalle Mah. Yanıkses Sok.Cem Karaca Kültür Merkezi Yanı",
                            FitnessCenterName = "Bakırköy Migros"
                        },
                        new
                        {
                            FitnessCenterID = 26,
                            Capacity = 200,
                            DistrictID = 14,
                            FitnessCenterAdress = "Flyinn Alışveriş ve Yaşam Merkezi Şenlikköy Mah., Harman Sok. No:48",
                            FitnessCenterName = "Flyinn"
                        },
                        new
                        {
                            FitnessCenterID = 27,
                            Capacity = 200,
                            DistrictID = 15,
                            FitnessCenterAdress = "Prof. Dr. Necmettin Erbakan Cad. Arterium 2. Kısım A blok",
                            FitnessCenterName = "Başakşehir"
                        },
                        new
                        {
                            FitnessCenterID = 28,
                            Capacity = 200,
                            DistrictID = 15,
                            FitnessCenterAdress = "Ziya Gökalp, Süleyman Demirel Blv",
                            FitnessCenterName = "Mall Of İstanbul"
                        },
                        new
                        {
                            FitnessCenterID = 29,
                            Capacity = 200,
                            DistrictID = 17,
                            FitnessCenterAdress = "Sinanpaşa Mah. Şair Nedim Cad. No.20/A",
                            FitnessCenterName = "Akaretler"
                        },
                        new
                        {
                            FitnessCenterID = 30,
                            Capacity = 200,
                            DistrictID = 17,
                            FitnessCenterAdress = "Kültür Mah. Nispetiye Cad. No:56",
                            FitnessCenterName = "Akmerkez"
                        },
                        new
                        {
                            FitnessCenterID = 31,
                            Capacity = 200,
                            DistrictID = 17,
                            FitnessCenterAdress = "Ulus, Lotus World No:6, Ambarlıdere Sok.",
                            FitnessCenterName = "Ortaköy Lotus"
                        },
                        new
                        {
                            FitnessCenterID = 32,
                            Capacity = 200,
                            DistrictID = 17,
                            FitnessCenterAdress = "Zorlu Center, Levazım Mah., Koru Sok. No:2",
                            FitnessCenterName = "Zorlu"
                        },
                        new
                        {
                            FitnessCenterID = 33,
                            Capacity = 200,
                            DistrictID = 18,
                            FitnessCenterAdress = "Göztepe Mah. Migros AVM, Atatürk Cad.",
                            FitnessCenterName = "Anadolu Hisarı"
                        },
                        new
                        {
                            FitnessCenterID = 34,
                            Capacity = 200,
                            DistrictID = 19,
                            FitnessCenterAdress = "Hüseyinağa Mah., Atıf Yılmaz Cad. No:5",
                            FitnessCenterName = "İstiklal AVM"
                        },
                        new
                        {
                            FitnessCenterID = 35,
                            Capacity = 200,
                            DistrictID = 20,
                            FitnessCenterAdress = "Akbatı AVM Sanayi Mah. 1655 Sok.No:6",
                            FitnessCenterName = "Akbatı"
                        },
                        new
                        {
                            FitnessCenterID = 36,
                            Capacity = 200,
                            DistrictID = 20,
                            FitnessCenterAdress = "Mevlana Mah., Çelebi Mehmet Cad. 33/A",
                            FitnessCenterName = "Marmara Park"
                        },
                        new
                        {
                            FitnessCenterID = 37,
                            Capacity = 200,
                            DistrictID = 20,
                            FitnessCenterAdress = "Turgut Özal Mah. E-5 Üzeri",
                            FitnessCenterName = "Torium"
                        },
                        new
                        {
                            FitnessCenterID = 38,
                            Capacity = 200,
                            DistrictID = 21,
                            FitnessCenterAdress = "Topçular Mah. Osman Gazi Cad. No:2",
                            FitnessCenterName = "Axis İstanbul"
                        },
                        new
                        {
                            FitnessCenterID = 39,
                            Capacity = 200,
                            DistrictID = 21,
                            FitnessCenterAdress = "Biz Cevahir Haliç AVM, Alibeyköy Mah., Vardar Blv. No:11 D:5",
                            FitnessCenterName = "Biz Cevahir"
                        },
                        new
                        {
                            FitnessCenterID = 40,
                            Capacity = 200,
                            DistrictID = 21,
                            FitnessCenterAdress = "Defterdar Mah., Otakçılar Cad. No:78",
                            FitnessCenterName = "Flat Ofis Haliç"
                        },
                        new
                        {
                            FitnessCenterID = 41,
                            Capacity = 200,
                            DistrictID = 21,
                            FitnessCenterAdress = "Göktürk Merkez Mah., İstanbul Cad. No:30",
                            FitnessCenterName = "Göktürk"
                        },
                        new
                        {
                            FitnessCenterID = 42,
                            Capacity = 200,
                            DistrictID = 21,
                            FitnessCenterAdress = "Yeşilpınar Mah. Girne Cad. 34065 Eyüp",
                            FitnessCenterName = "Vialand"
                        },
                        new
                        {
                            FitnessCenterID = 43,
                            Capacity = 200,
                            DistrictID = 22,
                            FitnessCenterAdress = "Güven Mah., Eski Londra Asfaltı Cad. No:89",
                            FitnessCenterName = "Kale Center"
                        },
                        new
                        {
                            FitnessCenterID = 44,
                            Capacity = 200,
                            DistrictID = 22,
                            FitnessCenterAdress = "E-5 Yolu Merter Sapağı, 3M Migros Binası, 1. Kat",
                            FitnessCenterName = "Merter"
                        },
                        new
                        {
                            FitnessCenterID = 45,
                            Capacity = 200,
                            DistrictID = 23,
                            FitnessCenterAdress = "Bağdat Caddesi, Göztepe Mahallesi, Birgen İş Merkezi No:226",
                            FitnessCenterName = "Cadde"
                        },
                        new
                        {
                            FitnessCenterID = 46,
                            Capacity = 200,
                            DistrictID = 23,
                            FitnessCenterAdress = "Caddebostan, Haldun Taner Sok. No:11",
                            FitnessCenterName = "CKM"
                        },
                        new
                        {
                            FitnessCenterID = 47,
                            Capacity = 200,
                            DistrictID = 23,
                            FitnessCenterAdress = "Tütüncü Mehmet Efendi Cad. Göztepe Loft Plaza, Kat:2-3",
                            FitnessCenterName = "Göztepe BX"
                        },
                        new
                        {
                            FitnessCenterID = 48,
                            Capacity = 200,
                            DistrictID = 23,
                            FitnessCenterAdress = "19 Mayıs Mah. Şemsettin Günaltay Cad. No:166/1",
                            FitnessCenterName = "Kazasker"
                        },
                        new
                        {
                            FitnessCenterID = 49,
                            Capacity = 200,
                            DistrictID = 23,
                            FitnessCenterAdress = "Kozzy AVM Kozyatağı Mah., Bayar Cad., Buket Sok. No:14",
                            FitnessCenterName = "Kozzy"
                        },
                        new
                        {
                            FitnessCenterID = 50,
                            Capacity = 200,
                            DistrictID = 23,
                            FitnessCenterAdress = "Suadiye Mah., Plaj Yolu Sok. No:18",
                            FitnessCenterName = "Suadiye"
                        },
                        new
                        {
                            FitnessCenterID = 51,
                            Capacity = 200,
                            DistrictID = 24,
                            FitnessCenterAdress = "Merkez Mah. Cendere Cad. No:28",
                            FitnessCenterName = "Axis Kağıthane"
                        },
                        new
                        {
                            FitnessCenterID = 52,
                            Capacity = 200,
                            DistrictID = 25,
                            FitnessCenterAdress = "Kordonboyu Mah., Ankara Cad. No:147",
                            FitnessCenterName = "İST Marina"
                        },
                        new
                        {
                            FitnessCenterID = 53,
                            Capacity = 200,
                            DistrictID = 25,
                            FitnessCenterAdress = "Petroliş Mah. Üsküdar Cad. No:29",
                            FitnessCenterName = "Kartal"
                        },
                        new
                        {
                            FitnessCenterID = 54,
                            Capacity = 200,
                            DistrictID = 26,
                            FitnessCenterAdress = "Atakent Mah. Çiçekli Vadi No:1",
                            FitnessCenterName = "Arena Park"
                        },
                        new
                        {
                            FitnessCenterID = 55,
                            Capacity = 200,
                            DistrictID = 27,
                            FitnessCenterAdress = "Aydınevler Mah., Çamlıca Sitesi Yolu Sok.",
                            FitnessCenterName = "Hilltown"
                        },
                        new
                        {
                            FitnessCenterID = 56,
                            Capacity = 200,
                            DistrictID = 27,
                            FitnessCenterAdress = "Ofispark, Altayçeşme Mah. E-5 Karayolu Üstü, Çam Sok.",
                            FitnessCenterName = "Maltepe Ofis Park"
                        },
                        new
                        {
                            FitnessCenterID = 57,
                            Capacity = 200,
                            DistrictID = 27,
                            FitnessCenterAdress = "Cevizli, Tugay Yolu Cd. No:71",
                            FitnessCenterName = "Maltepe Piazza"
                        },
                        new
                        {
                            FitnessCenterID = 58,
                            Capacity = 200,
                            DistrictID = 27,
                            FitnessCenterAdress = "Ritim İstanbul, Cevizli Mah. Zuhal Cad. Füsun Sokak",
                            FitnessCenterName = "Maltepe Ritim"
                        },
                        new
                        {
                            FitnessCenterID = 59,
                            Capacity = 200,
                            DistrictID = 28,
                            FitnessCenterAdress = "Çarşı Mah., E-5 Karayolu Tersane Kavşağı Elka Sok. No:9",
                            FitnessCenterName = "Neomarin"
                        },
                        new
                        {
                            FitnessCenterID = 60,
                            Capacity = 200,
                            DistrictID = 29,
                            FitnessCenterAdress = "42 Maslak Ahi Evran Cad. No:6",
                            FitnessCenterName = "42 Maslak"
                        },
                        new
                        {
                            FitnessCenterID = 61,
                            Capacity = 200,
                            DistrictID = 29,
                            FitnessCenterAdress = "İstinye Mah., Boğaziçi Sitesi No:2",
                            FitnessCenterName = "İstinye"
                        },
                        new
                        {
                            FitnessCenterID = 62,
                            Capacity = 200,
                            DistrictID = 29,
                            FitnessCenterAdress = "Uskumruköy Mah. Yorgancı Çiftliği Mevkii",
                            FitnessCenterName = "Orman Ada"
                        },
                        new
                        {
                            FitnessCenterID = 63,
                            Capacity = 200,
                            DistrictID = 29,
                            FitnessCenterAdress = "Ayazağa Mah., Cendere Cad. 109/C",
                            FitnessCenterName = "Vadi İstanbul"
                        },
                        new
                        {
                            FitnessCenterID = 64,
                            Capacity = 200,
                            DistrictID = 30,
                            FitnessCenterAdress = "Cumhuriyet Mah., Silahşör Cad., Yeniyol Sok. No:2",
                            FitnessCenterName = "Bomonti"
                        },
                        new
                        {
                            FitnessCenterID = 65,
                            Capacity = 200,
                            DistrictID = 30,
                            FitnessCenterAdress = "Cevahir AVM 19 Mayıs Mah.,Büyükdere Cad. 136/22",
                            FitnessCenterName = "Cevahir"
                        },
                        new
                        {
                            FitnessCenterID = 66,
                            Capacity = 200,
                            DistrictID = 30,
                            FitnessCenterAdress = "City’s AVM Teşvikiye Cd. No:12",
                            FitnessCenterName = "City's Nişantaşı"
                        },
                        new
                        {
                            FitnessCenterID = 67,
                            Capacity = 200,
                            DistrictID = 30,
                            FitnessCenterAdress = "Fulya Mah. Yeşilçimen Sok. Polat Towerside No:12/429",
                            FitnessCenterName = "Fulya"
                        },
                        new
                        {
                            FitnessCenterID = 68,
                            Capacity = 200,
                            DistrictID = 30,
                            FitnessCenterAdress = "Harbiye Mah, Kadırgalar Cad. No:3",
                            FitnessCenterName = "Gmall"
                        },
                        new
                        {
                            FitnessCenterID = 69,
                            Capacity = 200,
                            DistrictID = 30,
                            FitnessCenterAdress = "Halaskargazi Cd. No: 38-66",
                            FitnessCenterName = "Nişantaşı Lotus"
                        },
                        new
                        {
                            FitnessCenterID = 70,
                            Capacity = 200,
                            DistrictID = 30,
                            FitnessCenterAdress = "ÖzdilekPark AVM Büyükdere Cad. No:181",
                            FitnessCenterName = "Özdilek Park"
                        },
                        new
                        {
                            FitnessCenterID = 71,
                            Capacity = 200,
                            DistrictID = 30,
                            FitnessCenterAdress = "Fulya Mah., Akıncı Bayırı Sok. No:14",
                            FitnessCenterName = "Torun Center"
                        },
                        new
                        {
                            FitnessCenterID = 72,
                            Capacity = 200,
                            DistrictID = 31,
                            FitnessCenterAdress = "Atlaspark AVM Abdurrahmangazi Mah. Fatih Blv., No:67",
                            FitnessCenterName = "Atlas Park"
                        },
                        new
                        {
                            FitnessCenterID = 73,
                            Capacity = 200,
                            DistrictID = 32,
                            FitnessCenterAdress = "Yunus Emre Mah., Lütfi Aykaç Blv. No:81",
                            FitnessCenterName = "Vega"
                        },
                        new
                        {
                            FitnessCenterID = 74,
                            Capacity = 200,
                            DistrictID = 33,
                            FitnessCenterAdress = "İnkılap Mah., Küçüksu Cad.",
                            FitnessCenterName = "Akyaka Park"
                        },
                        new
                        {
                            FitnessCenterID = 75,
                            Capacity = 200,
                            DistrictID = 33,
                            FitnessCenterAdress = "Buyaka AVM FSM Mah. Balkan Cad. No:56",
                            FitnessCenterName = "Buyaka"
                        },
                        new
                        {
                            FitnessCenterID = 76,
                            Capacity = 200,
                            DistrictID = 33,
                            FitnessCenterAdress = "Necip Fazıl Mah. Mabeyn Cad. No:3A",
                            FitnessCenterName = "Metro Garden"
                        },
                        new
                        {
                            FitnessCenterID = 77,
                            Capacity = 200,
                            DistrictID = 33,
                            FitnessCenterAdress = "Atakent Mah., Mithatpaşa Cad. No:116",
                            FitnessCenterName = "Çağla Plaza"
                        },
                        new
                        {
                            FitnessCenterID = 78,
                            Capacity = 200,
                            DistrictID = 34,
                            FitnessCenterAdress = "Altunizade Mah. Mahir İz Cad. No:9/1B",
                            FitnessCenterName = "Altunizade"
                        },
                        new
                        {
                            FitnessCenterID = 79,
                            Capacity = 200,
                            DistrictID = 34,
                            FitnessCenterAdress = "Mehmet Akif Ersoy Mah., Bosna Blv. No:99",
                            FitnessCenterName = "Çengelköy Park"
                        },
                        new
                        {
                            FitnessCenterID = 80,
                            Capacity = 200,
                            DistrictID = 34,
                            FitnessCenterAdress = "Ünalan Mah., Libadiye Cad. No: 82F",
                            FitnessCenterName = "Emaar Square"
                        },
                        new
                        {
                            FitnessCenterID = 81,
                            Capacity = 200,
                            DistrictID = 34,
                            FitnessCenterAdress = "Mimar Sinan Mah., Çavuşdere Cad. No:35",
                            FitnessCenterName = "Nev Çarsı AVM"
                        },
                        new
                        {
                            FitnessCenterID = 82,
                            Capacity = 200,
                            DistrictID = 35,
                            FitnessCenterAdress = "İnciraltı, Mithatpaşa Cd. No:46",
                            FitnessCenterName = "Balçova Kipa"
                        },
                        new
                        {
                            FitnessCenterID = 83,
                            Capacity = 200,
                            DistrictID = 36,
                            FitnessCenterAdress = "Kazım Dirik Mah. 367/6 Sok. No:3/5",
                            FitnessCenterName = "Kids Mall"
                        },
                        new
                        {
                            FitnessCenterID = 84,
                            Capacity = 200,
                            DistrictID = 36,
                            FitnessCenterAdress = "4174 Sok. No:4 Bağburnu Mevkii",
                            FitnessCenterName = "Point Bornova"
                        },
                        new
                        {
                            FitnessCenterID = 85,
                            Capacity = 200,
                            DistrictID = 37,
                            FitnessCenterAdress = "Adatepe Mah. 62/7 Sok. No:1",
                            FitnessCenterName = "Buca"
                        },
                        new
                        {
                            FitnessCenterID = 86,
                            Capacity = 200,
                            DistrictID = 38,
                            FitnessCenterAdress = "Cahar Dudayev Blv., Koçtaş 7/201",
                            FitnessCenterName = "Mavi Şehir Koçtaş"
                        },
                        new
                        {
                            FitnessCenterID = 87,
                            Capacity = 200,
                            DistrictID = 39,
                            FitnessCenterAdress = "Binbaşı Reşatbey, Akçay Cad. No:101",
                            FitnessCenterName = "Gaziemir Optimum"
                        },
                        new
                        {
                            FitnessCenterID = 88,
                            Capacity = 200,
                            DistrictID = 40,
                            FitnessCenterAdress = "Çınarlı Mah. Ozan Abay Cad. No:8/309",
                            FitnessCenterName = "Ege Perla"
                        },
                        new
                        {
                            FitnessCenterID = 89,
                            Capacity = 200,
                            DistrictID = 40,
                            FitnessCenterAdress = "Alsancak Mah., Kıbrıs Şehitleri Cad. No: 131",
                            FitnessCenterName = "Kıbrıs Şehitleri"
                        },
                        new
                        {
                            FitnessCenterID = 90,
                            Capacity = 200,
                            DistrictID = 41,
                            FitnessCenterAdress = "Tatlıkuyu Mah., Güney Yanyol Cad. No:310",
                            FitnessCenterName = "Gebze Center"
                        },
                        new
                        {
                            FitnessCenterID = 91,
                            Capacity = 200,
                            DistrictID = 42,
                            FitnessCenterAdress = "Körfez Mah., Ömer Türkçakal Blv.",
                            FitnessCenterName = "41 Burda"
                        },
                        new
                        {
                            FitnessCenterID = 92,
                            Capacity = 200,
                            DistrictID = 43,
                            FitnessCenterAdress = "Eğriçam Mah., 2224. Sok.",
                            FitnessCenterName = "Örs Plaza"
                        },
                        new
                        {
                            FitnessCenterID = 93,
                            Capacity = 200,
                            DistrictID = 44,
                            FitnessCenterAdress = "Ortakentyahşi Mah., Cumhuriyet Cad. Kemer Mevkii No:6",
                            FitnessCenterName = "Bodrum Midtown"
                        },
                        new
                        {
                            FitnessCenterID = 94,
                            Capacity = 200,
                            DistrictID = 45,
                            FitnessCenterAdress = "Agora AVM  Arabacı Alanı Mah. Kasım Paşa Cad. No:10",
                            FitnessCenterName = "Agora"
                        },
                        new
                        {
                            FitnessCenterID = 95,
                            Capacity = 200,
                            DistrictID = 46,
                            FitnessCenterAdress = "Yenimahalle, Çarşamba Cd. No:52",
                            FitnessCenterName = "Samsun Piazza"
                        });
                });

            modelBuilder.Entity("Antreman.Models.FitnessCenterSubCat", b =>
                {
                    b.Property<int>("FitnessCenterSubCatID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FitnessCenterSubCatID"));

                    b.Property<int>("FitnessCenterID")
                        .HasColumnType("int");

                    b.Property<int>("SubCategoryID")
                        .HasColumnType("int");

                    b.HasKey("FitnessCenterSubCatID");

                    b.HasIndex("FitnessCenterID");

                    b.HasIndex("SubCategoryID");

                    b.ToTable("FitnessCenterSubCat");
                });

            modelBuilder.Entity("Antreman.Models.Gender", b =>
                {
                    b.Property<int>("GenderID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GenderID"));

                    b.Property<string>("GenderName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("GenderID");

                    b.ToTable("Genders");

                    b.HasData(
                        new
                        {
                            GenderID = 1,
                            GenderName = "Kadın"
                        },
                        new
                        {
                            GenderID = 2,
                            GenderName = "Erkek"
                        });
                });

            modelBuilder.Entity("Antreman.Models.Rolee", b =>
                {
                    b.Property<byte>("RoleeID")
                        .HasColumnType("tinyint");

                    b.Property<string>("RoleeName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("RoleeID");

                    b.ToTable("Rolees");

                    b.HasData(
                        new
                        {
                            RoleeID = (byte)1,
                            RoleeName = "Aday"
                        },
                        new
                        {
                            RoleeID = (byte)2,
                            RoleeName = "Uye"
                        },
                        new
                        {
                            RoleeID = (byte)3,
                            RoleeName = "Admin"
                        },
                        new
                        {
                            RoleeID = (byte)4,
                            RoleeName = "Supervisor"
                        });
                });

            modelBuilder.Entity("Antreman.Models.SubCategory", b =>
                {
                    b.Property<int>("SubCategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SubCategoryID"));

                    b.Property<int>("CategoryID")
                        .HasColumnType("int");

                    b.Property<string>("SubCategoryName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("SubCategoryID");

                    b.HasIndex("CategoryID");

                    b.ToTable("SubCategories");

                    b.HasData(
                        new
                        {
                            SubCategoryID = 1,
                            CategoryID = 1,
                            SubCategoryName = "Kardiyo"
                        },
                        new
                        {
                            SubCategoryID = 2,
                            CategoryID = 1,
                            SubCategoryName = "Kuvvet"
                        },
                        new
                        {
                            SubCategoryID = 3,
                            CategoryID = 1,
                            SubCategoryName = "HIIT"
                        },
                        new
                        {
                            SubCategoryID = 4,
                            CategoryID = 1,
                            SubCategoryName = "Karın"
                        },
                        new
                        {
                            SubCategoryID = 5,
                            CategoryID = 1,
                            SubCategoryName = "Pilates"
                        },
                        new
                        {
                            SubCategoryID = 6,
                            CategoryID = 1,
                            SubCategoryName = "Yoga"
                        },
                        new
                        {
                            SubCategoryID = 7,
                            CategoryID = 1,
                            SubCategoryName = "Esneklik"
                        },
                        new
                        {
                            SubCategoryID = 8,
                            CategoryID = 1,
                            SubCategoryName = "Dans"
                        },
                        new
                        {
                            SubCategoryID = 9,
                            CategoryID = 1,
                            SubCategoryName = "Cycle"
                        },
                        new
                        {
                            SubCategoryID = 10,
                            CategoryID = 2,
                            SubCategoryName = "Kilo Vermek"
                        },
                        new
                        {
                            SubCategoryID = 11,
                            CategoryID = 2,
                            SubCategoryName = "Kas Kazanmak"
                        },
                        new
                        {
                            SubCategoryID = 12,
                            CategoryID = 2,
                            SubCategoryName = "Formu Korumak"
                        },
                        new
                        {
                            SubCategoryID = 13,
                            CategoryID = 2,
                            SubCategoryName = "Dayanıklılığı Arttırmak"
                        });
                });

            modelBuilder.Entity("Antreman.Models.Userr", b =>
                {
                    b.Property<int>("UserrID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserrID"));

                    b.Property<string>("Emaill")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Passwordd")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<byte>("RoleeID")
                        .HasColumnType("tinyint");

                    b.HasKey("UserrID");

                    b.HasIndex("RoleeID");

                    b.ToTable("Userrs");

                    b.HasData(
                        new
                        {
                            UserrID = 1,
                            Emaill = "aday@gmail.com",
                            Passwordd = "123456",
                            RoleeID = (byte)1
                        },
                        new
                        {
                            UserrID = 2,
                            Emaill = "uye@gmail.com",
                            Passwordd = "123456",
                            RoleeID = (byte)2
                        },
                        new
                        {
                            UserrID = 3,
                            Emaill = "uye2@gmail.com",
                            Passwordd = "123456",
                            RoleeID = (byte)2
                        },
                        new
                        {
                            UserrID = 4,
                            Emaill = "admin@gmail.com",
                            Passwordd = "123456",
                            RoleeID = (byte)3
                        },
                        new
                        {
                            UserrID = 5,
                            Emaill = "supervisor@gmail.com",
                            Passwordd = "123456",
                            RoleeID = (byte)4
                        });
                });

            modelBuilder.Entity("Antreman.Models.Commentt", b =>
                {
                    b.HasOne("Antreman.Models.FitnessCenter", "FitnessCenter")
                        .WithMany()
                        .HasForeignKey("FitnessCenterID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Antreman.Models.Userr", "Userr")
                        .WithMany()
                        .HasForeignKey("UserrID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FitnessCenter");

                    b.Navigation("Userr");
                });

            modelBuilder.Entity("Antreman.Models.District", b =>
                {
                    b.HasOne("Antreman.Models.City", "City")
                        .WithMany()
                        .HasForeignKey("CityID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("Antreman.Models.Favoritee", b =>
                {
                    b.HasOne("Antreman.Models.FitnessCenter", "FitnessCenter")
                        .WithMany()
                        .HasForeignKey("FitnessCenterID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Antreman.Models.Userr", "Userr")
                        .WithMany()
                        .HasForeignKey("UserrID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FitnessCenter");

                    b.Navigation("Userr");
                });

            modelBuilder.Entity("Antreman.Models.FitnessCenter", b =>
                {
                    b.HasOne("Antreman.Models.District", "District")
                        .WithMany()
                        .HasForeignKey("DistrictID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("District");
                });

            modelBuilder.Entity("Antreman.Models.FitnessCenterSubCat", b =>
                {
                    b.HasOne("Antreman.Models.FitnessCenter", "FitnessCenter")
                        .WithMany()
                        .HasForeignKey("FitnessCenterID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Antreman.Models.SubCategory", "SubCategory")
                        .WithMany()
                        .HasForeignKey("SubCategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FitnessCenter");

                    b.Navigation("SubCategory");
                });

            modelBuilder.Entity("Antreman.Models.SubCategory", b =>
                {
                    b.HasOne("Antreman.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Antreman.Models.Userr", b =>
                {
                    b.HasOne("Antreman.Models.Rolee", "Rolee")
                        .WithMany()
                        .HasForeignKey("RoleeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rolee");
                });
#pragma warning restore 612, 618
        }
    }
}
